apiVersion: apps/v1
kind: Deployment
metadata:
  name: clankair-shakur
  annotations:
    app.openshift.io/vcs-ref: v1.0.0
    app.openshift.io/vcs-uri: https://github.com/wiesmak/clankairshakur.git
  labels:
    app.kubernetes.io/name: clankair-shakur
    app.kubernetes.io/instance: clankair-shakur-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: clankair-shakur
      app.kubernetes.io/instance: clankair-shakur-bot
  template:
    metadata:
      labels:
        app.kubernetes.io/name: clankair-shakur
        app.kubernetes.io/instance: clankair-shakur-bot
    spec:
      containers:
        - name: bot
          image: image-registry.openshift-image-registry.svc:5000/clankair-shakur/clankair-shakur:v1.0.0
          imagePullPolicy: Always
          resources: {}
          env:
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: clankair-shakur
                  key: discord-token
            - name: THREAD_LIMIT
              valueFrom:
                configMapKeyRef:
                  name: clankair-shakur
                  key: thread-limit
                  optional: true
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
      serviceAccountName: clankair-shakur