apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-clankair-shakur
spec:
  params:
    - name: repo-url
      type: string
    - name: revision
      type: string
      default: master
    - name: image-tag
      type: string
      default: latest
    - name: image
      type: string
      default: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/clankair-shakur:$(params.image-tag)

  workspaces:
    - name: source

  tasks:
    - name: clone
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines
      workspaces:
        - name: output
          workspace: source
      params:
        - name: URL
          value: $(params.repo-url)
        - name: REVISION
          value: $(params.revision)

    - name: build
      runAfter:
        - clone
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: buildah
          - name: namespace
            value: openshift-pipelines
      workspaces:
        - name: source
          workspace: source
      params:
        - name: IMAGE
          value: $(params.image)
        - name: DOCKERFILE
          value: ./Dockerfile
        - name: CONTEXT
          value: .
        - name: TLSVERIFY
          value: "true"