apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: build-clankair-shakur-
spec:
  pipelineRef:
    name: build-clankair-shakur

  serviceAccountName: pipeline

  params:
    - name: repo-url
      value: https://github.com/wiesmak/clankairshakur.git

    - name: revision
      value: master

  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce

          resources:
            requests:
              storage: 2Gi